# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=1, verbose_name=b'Numara'),
            preserve_default=False,
        ),
    ]
